### ISSUE TITLE
Create GitHub actions workflows for `YYYY-MM-DD` releases

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenScPCA-analysis#30]
Related to: #28

There are two workflows we need to create – the first is for **cutting the release**, which we'd likely us `workflow_dispatch` to do:

 ```
    - name: Get date
      run: echo "TODAY=$(date -I)" >> $GITHUB_ENV
    - name: Create dated release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.TODAY }}
  ```
  
  But we also need a GitHub action workflow to file a release issue regularly to remind us to cut a release.
