### ISSUE TITLE
Ensure fetusref.SeuratData is versioned in cell-type-wilms-tumor-06

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#830]
Currently, this module is installing `fetusref.SeuratData` from a script with `SeuratData::InstallData()`. This may not be stable in the long-term, so we'd like a different approach to downloading this reference in a more robsut way. 

First, we've observed that the data itself is an R package. We might like to track this more formally with `renv`, since the dataset itself is a versioned package that lives at `http://seurat.nygenome.org/src/contrib/fetusref.SeuratData_1.0.0.tar.gz`. For this, we'd need to:
- [ ] First, test whether and how exactly to track this in `renv`. In some local testing, there may be system dependencies that this is installing when you restore a `renv` environment where this package is tracked. Mac isn't granting permissions (reasonably) to install those deps, so we'll want to test whether an environment can indeed be restored on a LSfR instance, whether other dependencies are needed, and further how exactly (if it's not intuitive) to load the package to be able to access the data.
- [ ] Update renv to track this package. This should be in a PR by itself since the Docker image will need to be built
- [ ] Update code to no longer install this package

But, step 1 may not pan out, and/or it may be a rabbit hole. Alternatives are therefore to download the reference directly from one of these two spots, save it in `scratch`, and then load it up with `Azimuth::LoadReference()`. 
- `curl https://seurat.nygenome.org/src/contrib/fetusref.SeuratData_1.0.0.tar.gz` and manually pull out the dataset for use. The reference data lives in `inst/azimuth`.
- Download the reference from where it permanently lives in Zenodo: https://zenodo.org/records/4738021#.YJIW4C2ZNQI. **This is probably my preference**, since I am most confident the Zenodo DOI will continue to exist indefinitely, but the Seurat links may change in the future.

**Comment by jashapiro** [comment]
> [ ] First, test whether and how exactly to track this in `renv`. In some local testing, there may be system dependencies that this is installing when you restore a `renv` environment where this package is tracked. Mac isn't granting permissions (reasonably) to install those deps, so we'll want to test whether an environment can indeed be restored on a LSfR instance, whether other dependencies are needed, and further how exactly (if it's not intuitive) to load the package to be able to access the data.

Did you try installing this package with `renv::install("https://seurat.nygenome.org/src/contrib/fetusref.SeuratData_1.0.0.tar.gz")` ?

When I did so I had no trouble with restoring the environment, and I am actually quite surprised to hear that there is any attempt to install system packages. That is not normal `renv` behavior (though I think it can occur with `pak`).

**Comment by sjspielman** [comment]
I had no issue restoring from my _work computer_, but when I tried on my personal computer (which notably didn't have caches for many packages, but was otherwise setup for computing), it failed repeatedly over those sorts of dependencies when attempting to restore that package specifically.

**Comment by jashapiro** [comment]
> I had no issue restoring from my _work computer_, but when I tried on my personal computer (which notably didn't have caches for many packages, but was otherwise setup for computing), it failed repeatedly over those sorts of dependencies when attempting to restore that package specifically.

I strongly suspect then that it was not that package, which is extraordinarily simple in content, but may well have been one of its dependencies.

**Comment by jashapiro** [comment]
Another thing I noticed is that this module installed `Seurat` via GitHub rather than CRAN, which probably makes it much more fiddly than it needs to be, as there is no option to install binaries.

**Comment by sjspielman** [comment]
I have no explanation, just frustrations... Dependencies seem similarly benign... Hence, in the interest of time, I tend to prefer Zenodo since it doesn't involve digging down a rabbit hole, but you are welcome to dig more if you like!

```
Package: fetusref.SeuratData
Title: Azimuth Reference: fetus
Version: 1.0.0
Date: 2022-03-28
Authors@R: 
    person("Satija", "Lab", email = "seurat@nygenome.org", role = c("aut", "cre"))
Description: 
  species: human
  system: fetus
  ncells: 377456
License: CC BY 4.0
Encoding: UTF-8
Roxygen: list(packages = "exdata")
RoxygenNote: 7.1.2
Suggests: curl, desc, exdata, pkgload, rprojroot, tools, usethis
Remotes: mojaveazure/exdata
Depends: R (>= 3.5.0), SeuratObject (>= 4.0.4)
NeedsCompilation: no
Packaged: 2022-04-25 21:31:17 UTC; hartmana
Author: Satija Lab [aut, cre]
Maintainer: Satija Lab <seurat@nygenome.org>
```
